### ISSUE TITLE
Return data of the task on the event listener

### ISSUE THREAD

**Issue by FelipeFernandesLeandro** [dzek69/queue-system#16]
Would be nice to get some data of the task on the event listener like:

```
const database = DatabaseService();
const databaseQueue = new Queue();
databaseQueue.addEventListener(EVENTS.TASK_SUCCESS, (message) => {
    console.log(message as string);
  });
databaseQueue.add(async () => await database.insertMessage(message)); // database.insertMessage returns a string
```

**Comment by dzek69** [comment]
Hey, thanks for suggestion, it seems like a good idea, on the weekend I'll try upgrading the lib some more

**Comment by dzek69** [comment]
Hello,
Your request is fulfilled 🎉 

While it was perfectly possible to achieve this without modifications it required a async listener though:
```javascript
databaseQueue.addEventListener(EVENTS.TASK_SUCCESS, async (task) => {
   const data = await task.promise;
});
```

This is still valid, new changes are backwards compatible. However if you don't want `async` listener you can now do this:
```javascript
databaseQueue.addEventListener(EVENTS.TASK_SUCCESS, (task, result) => {
  console.log(result); // result is type of unknown, you can do runtime type check or typecast if you are sure
});
```

Event listeners are now much better typed, you don't have to guess the types of arguments of your listeners.

I encourage you to install new `4.1.0` version. Updated docs are here: https://dzek69.github.io/queue-system/

Please let me know if this solves your issue or close it yourself.
